repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: mixed-line-ending
        args: [ "--fix=lf" ]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: name-tests-test
      - id: pretty-format-json
        name: pretty format json
        description: sets a standard for formatting json files.
        entry: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
          - "--no-ensure-ascii"
      - id: check-added-large-files
        args: ["--maxkb=1024"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
