from enum import StrEnum


class States(StrEnum):
    DEFAULT = "default"
    START = "start"
    PRICE = "price"
    REGISTRATION = "registration"
    DINNER = "dinner"
    SCHEDULE = "schedule"

    DAY_1ND = "schedule-first-day"
    DAY_1ND_OPEN_AIR = "schedule-openair"
    DAY_1ND_LOC_PARTY = "schedule-location-party-first-day"

    DAY_2ND = "schedule-second-day"
    DAY_2ND_1_LES = "schedule-2nd-day-1-lesson"
    DAY_2ND_1_LES_BEG = "schedule-2nd-day-1-lesson-beg"
    DAY_2ND_1_LES_INT = "schedule-2nd-day-1-lesson-int"
    DAY_2ND_2_LES = "schedule-2nd-day-2-lesson"
    DAY_2ND_2_LES_INT = "schedule-2nd-day-2-lesson-int"
    DAY_2ND_2_LES_ADV = "schedule-2nd-day-2-lesson-adv"
    DAY_2ND_3_LES = "schedule-2nd-day-3-lesson"
    DAY_2ND_3_LES_BEG = "schedule-2nd-day-3-lesson-beg"
    DAY_2ND_3_LES_ADV = "schedule-2nd-day-3-lesson-adv"
    DAY_2ND_4_LES = "schedule-2nd-day-bonus"
    DAY_2ND_4_LES_1 = "schedule-2nd-day-bonus-1"
    DAY_2ND_4_LES_2 = "schedule-2nd-day-bonus-2"
    DAY_2ND_PARTY = "schedule-party-second-day"
    DAY_2ND_LOC_PARTY = "schedule-location-party-second-day"

    DAY_3ND = "schedule-third-day"
    DAY_3ND_PARTY = "schedule-party-third-day"
    DAY_3ND_1_LES = "schedule-3rd-day-yoga"
    DAY_3ND_2_LES = "schedule-3rd-day-2-lesson"
    DAY_3ND_2_LES_BEG = "schedule-3rd-day-2-lesson-beg"
    DAY_3ND_2_LES_INT = "schedule-3rd-day-2-lesson-int"
    DAY_3ND_3_LES = "schedule-3rd-day-3-lesson"
    DAY_3ND_3_LES_INT = "schedule-3rd-day-3-lesson-int"
    DAY_3ND_3_LES_ADV = "schedule-3rd-day-3-lesson-adv"
    DAY_3ND_4_LES = "schedule-3rd-day-bonus"
    DAY_3ND_4_LES_BONUS = "schedule-3rd-day-bonus-1"
    DAY_3ND_4_LES_ADV = "schedule-3rd-day-4-lesson-adv"
    DAY_3ND_LOC_PARTY = "schedule-location-party-third-day"

    LOCATION = "location"
    LOCATION_SDS = "location-sds"
    LOCATION_PARTY = "location-party"
    LOCATION_OPENAIR = "location-openair"

    LEVELS = "levels"
    CHAT = "chat"
    CONTACTS = "contacts"
