services:
  bot:
    build: .
    restart: unless-stopped
    stop_signal: SIGINT
    ports:
      - "127.0.0.1:8011:8011"
    environment:
      PYTHONUNBUFFERED: 1
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    networks:
      - redis-private-net

networks:
  redis-private-net:
    external: true
